//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int planID { get; set; }
        public decimal weeklyTransferLimit { get; set; }
        public decimal singleTransferLimit { get; set; }
        public decimal weeklyPaymentLimit { get; set; }
    }
}
