//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPaymentToken
    {
        public int requestPaymentTokenID { get; set; }
        public int requestID { get; set; }
        public int payorTokenID { get; set; }
    }
}
