//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPayment
    {
        public int requestID { get; set; }
        public int payeeUserID { get; set; }
        public System.DateTime requestDateTime { get; set; }
        public decimal amount { get; set; }
        public string memo { get; set; }
    }
}
