//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendPayment
    {
        public int paymentID { get; set; }
        public int payorUserID { get; set; }
        public int payeeTokenID { get; set; }
        public System.DateTime paymentDateTime { get; set; }
        public decimal amount { get; set; }
        public string memo { get; set; }
        public bool isCancelled { get; set; }
    }
}
