//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int tokenID { get; set; }
        public int userID { get; set; }
        public int tokentype { get; set; }
        public string email { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public bool isVerifiedToken { get; set; }
    }
}
