//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userID { get; set; }
        public int planID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> SSN { get; set; }
        public decimal balance { get; set; }
        public string email { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string password { get; set; }
        public Nullable<int> loginStatus { get; set; }
    }
}
