//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIJN
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BankAccounts = new HashSet<BankAccount>();
            this.payments = new HashSet<payment>();
            this.payments1 = new HashSet<payment>();
        }
    
        public int userID { get; set; }
        public int planID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> SSN { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string password { get; set; }
        public Nullable<int> loginStatus { get; set; }
    
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<payment> payments1 { get; set; }
    }
}
